[package]
name = "wasm-futures-executor"
version = "0.1.0"
edition = "2018"
authors = ["Oliver Wangler <oliver@wngr.de>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
futures = "0.3.16"
futures-task = "0.3.16"
instant = { version = "0.1.10", features = ["stdweb"] }
js-sys = "0.3.53"
log = "0.4.14"
wasm-bindgen = "0.2.76"
wasm-bindgen-futures = "0.4.26"

[dependencies.parking_lot]
version = "0.11.1"
# nightly: use a thread parker with atomics support
features = ["wasm-bindgen", "stdweb", "nightly"]

[dependencies.web-sys]
version = "0.3.53"
features = ["DedicatedWorkerGlobalScope", "MessageEvent", "Navigator", "Worker", "WorkerOptions", "WorkerType", "ErrorEvent"]

[patch.crates-io]
js-sys = { path = "../wasm-bindgen/crates/js-sys" }
wasm-bindgen = { path = "../wasm-bindgen" }
wasm-bindgen-futures = { path = "../wasm-bindgen/crates/futures" }
web-sys = { path = "../wasm-bindgen/crates/web-sys" }
