[package]
name = "wasm-thread-pool"
version = "0.1.0"
edition = "2018"
authors = ["Oliver Wangler <oliver@wngr.de>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
futures = "0.3.16"
js-sys = "0.3.53"
log = "0.4.14"
parking_lot = { version = "0.11.1", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2.76"
wasm-bindgen-futures = "0.4.26"
web-sys = { version = "0.3.53", features = ["DedicatedWorkerGlobalScope", "MessageEvent", "Worker", "WorkerOptions", "WorkerType", "ErrorEvent"] }

[patch.crates-io]
js-sys = { path = "../wasm-bindgen/crates/js-sys" }
wasm-bindgen = { path = "../wasm-bindgen" }
wasm-bindgen-futures = { path = "../wasm-bindgen/crates/futures" }
web-sys = { path = "../wasm-bindgen/crates/web-sys" }
