[package]
name = "wasm-futures-executor"
version = "0.1.0"
edition = "2018"
authors = ["Oliver Wangler <oliver@wngr.de>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
futures = "0.3.16"
futures-task = "0.3.16"
instant = { version = "0.1.10", features = ["stdweb"] }
js-sys = "0.3.53"
log = "0.4.14"
wasm-bindgen = "0.2.76"
wasm-bindgen-futures = "0.4.26"

[dependencies.parking_lot]
version = "0.11.1"
# nightly: use a thread parker with atomics support
features = ["wasm-bindgen", "stdweb", "nightly"]

[dependencies.web-sys]
version = "0.3.53"
features = ["Blob", "BlobPropertyBag", "DedicatedWorkerGlobalScope", "MessageEvent", "Navigator", "Worker", "WorkerOptions", "WorkerType", "ErrorEvent", "Url"]

[patch.crates-io]
js-sys = { git = "https://github.com/rustwasm/wasm-bindgen", rev = "6ab9ac0f0f6853e1ceed8006a0ffe3a4c0c8323f" }
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen", rev = "6ab9ac0f0f6853e1ceed8006a0ffe3a4c0c8323f" }
wasm-bindgen-futures = { git = "https://github.com/rustwasm/wasm-bindgen", rev = "6ab9ac0f0f6853e1ceed8006a0ffe3a4c0c8323f" }
web-sys = { git = "https://github.com/rustwasm/wasm-bindgen", rev = "6ab9ac0f0f6853e1ceed8006a0ffe3a4c0c8323f" }
