on: [push, pull_request]

name: wasm-futures-executor

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: setup rustup
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y

    - name: cargo fmt
      run: cargo fmt --all -- --check

    - name: cargo clippy
      run: cargo clippy --workspace --examples --tests --all-features -- -D warnings
    
    - name: cargo build
      run: cargo build --locked

    - name: build sample
      run: cd sample && cargo install wasm-bindgen-cli && ./build.sh

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: build sample-webpack
      run: cd sample-webpack && cargo install wasm-pack && npm i && npm run build

    - name: build factorial 
      run: cd factorial && cargo install wasm-bindgen-cli && ./build.sh
